### ISSUE TITLE
leere ordner killen anwendung

### ISSUE THREAD

**Issue by WasMachenSachen** [mi-classroom/mi-web-technologien-beiboot-ss2021-WasMachenSachen#17]

**Comment by WasMachenSachen** [comment]
@yannic-bruegger hast du zufällig noch die Ordner Struktur welche damals die Anwendung zum Absturz gebracht hat?
wenn nicht auch nicht wild, kann es nur im Moment nicht mehr reproduzieren.

**Comment by WasMachenSachen** [comment]
@yannic-bruegger ping

**Comment by yannic-bruegger** [comment]
Huh. Wtf. Weiß nicht wann ich eine notification bekomme und wann nicht. 

Habe mir inzwischen leider auch nur noch die neue Ordnerstruktur.

**Comment by WasMachenSachen** [comment]
alles klar.
closed weil nicht mehr reproduzierbar.
